# Generated by Django 4.2.5 on 2023-11-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_alter_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='id2',
            field=models.IntegerField(default=0),
        ),
    ]
