# Generated by Django 4.2.5 on 2023-11-06 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_task_id2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id2',
        ),
    ]
